less/less.js

lib/less/functions/types.js, test/css/functions.css, test/less/functions.less
Currently `isunit(32, '')` evaluates with a cryptic error message: "error evaluating function `isunit`: Object [object Object] has no method 'toUpperCase'. Expected behaviour: it should evaluate to `true` without an error.
=> Fix isunit() not able to check if dimension has no unit.

lib/less/index.js, lib/less/parse.js, lib/less/render.js
Converting a Less stylesheet into an AST is a valuable piece of functionality, and worthy of being easily accessible to consumers of less.js. There have been issues submitted in the past about accessing the AST generated by the LESS parser, and without copy/pasting much of the code found within `lib/render.js`, it has thus far been a difficult task.
This pull request strips the parsing functionality out of `render.js` and moves it to `parse.js`, making it a top level property of the `less` module. In the same way that `less.render` takes a less string and returns a css string, `less.parse` takes a less string and returns a less AST.
I would also like to propose having the option to have extra data attached to this AST (for example, line/column location information for tokens like rules, …
=> Expose Less parsing as a top level feature of the less package

lib/less/functions/data-uri.js
As far as i understand does the logger.warn() function not accept such string neither has Less a built-in string format  function?
=> Better output for the warning when file size exceeds

lib/less/visitors/extend-visitor.js
See discussion in #1618 -- This seems to be the solution:
> parent_ids contains all the selectors which this extend has to draw from. If the extend has more than one parent, it's a reference done in another selector.
I don't know if you can test for warnings in the current setup. The test output for `extend_chaining` seems to be correct.
=> making sure :extend warning does not bubble up, fixes #1618

lib/less/functions/color.js, lib/less/functions/svg.js, lib/less/tree/color.js, test/css/variables.css, test/less/variables.less
Fixes:
```
@blue: bar;
@baz: blue;
div {
foo: @@baz;
}
```
For more details see [#1604 comments](https://github.com/less/less.js/pull/1604/files#issuecomment-37551900) and https://github.com/less/less.js/pull/2378.
=> Colour keyword as variable name reference

.gitignore, bin/lessc, lib/less/functions/data-uri.js, lib/less/import-manager.js, test/copy-bom.js, test/index.js, test/less-test.js
BOM bytes weren't being removed when @import'ing files, which can lead to syntax errors, etc.
As a bonus, this modifies the test functions to perform a second set of tests--a copy of the "test/less" folder is made as "test/less-bom", BOMs are inserted into each CSS and LESS file during the copy, and each test is ran for both folders.  The copy is performed anytime the tests are ran if the less-bom folder doesn't exist or is empty.
=> Remove BOM in imports.

lib/less/functions/types.js, test/css/functions.css, test/less/functions.less
As discussed in #1549, add a function for ruleset type check.
=> add support for `isruleset`

lib/less-node/lessc-helper.js
explain inline maps are as base64 data uri's
=> explain inline maps

lib/less/tree/ruleset.js, test/css/mixins-important.css, test/less/mixins-important.less
This should fix #2394
The issue was not with mixin being parametric, the problem was that variables of nested mixins did not evaluated properly.
=> Important on parametrized mixin 

lib/less/parser/parser.js, test/css/selectors.css, test/less/selectors.less
Added pseudoselector symbol `:` into set of characters that allow curly variable after them. #1294
=> Allow selector interpolation inside pseudoselectors. #1294

lib/less/render.js
less does not handle pathroot option without "/" at the end
e.g, ```data-rootpath=".."``` or ```-rp=..``` with this code
```css
backgroud-image: url("imgs/pic.png")
```
will outputs:
```css
backgroud-image: url("..imgs/pic.png")
```
instead of
```css
backgroud-image: url("../imgs/pic.png")
```
**NOTE:** I'm not sure if others options need this check too (e.g: --source-map-rootpath,...)
=> fix rootpath without / at the end handling

lib/less/parser/parser-input.js, lib/less/parser/parser.js
possible fix for https://github.com/less/less.js/issues/2370
I have used the following command to test this issue: `printf "p {\r//less\rc:1;\r}\r" | lessc -`
I'm not sure if this the most efficient fix.
I also tried `var nextNewLine = inp.substr(parserInput.i + 1).search(/\n|\r/);` to replace the `indexOf` but then i expect possible mismatches for `\r\n` which match on the first `\r`.
=> endlines and comments

lib/less/tree/ruleset.js, test/css/selectors.css, test/less/selectors.less
Selector composed from multiple joined selectors should keep original extends. #2206
=> Bug: extend doesn't work when appended on nested selector with &

lib/less/tree/mixin-definition.js, lib/less/tree/ruleset.js, test/css/mixins-important.css, test/less/mixins-important.less
Fixing `makeImportant` on mixins and rulesets: #2421
* Rulesets `makeImportant` must create a new ruleset.
* Mixin-definition `makeImportant` must create a new mixin definition. It must not convert mixin into ruleset.
Why eval failed: mixin-definition inherited `makeImportant` function from ruleset. As `makeImportant` cascaded to nested objects, every nested mixin was converted into ruleset and lost all parameters, conditions, etc. 
So, nested `set-width(@aaa)` in following code:
````
.size(@aaa) {
.set-width(@aaa) {
width: @aaa; 
}
.set-width(@aaa);
}
.when-calling-nested-with-param-issue-2394 {
.size(10px) !important;
}
````
was transformed into:
````
.when-calling-nested-with-param-issue-2394 {
.set-width {
width: @aaa; //fails on undefined variable
}
.set-width(10px);
}
````
which …
=> Nested mixin changing important 2421

lib/less/source-map-builder.js, test/index.js, test/less-test.js, test/less/sourcemaps-empty/var-defs.less
=> Fix empty sourcemaps

lib/less/functions/svg.js, test/browser/less/urls.less, test/less/errors/svg-gradient2.txt, test/less/errors/svg-gradient3.txt, test/less/errors/svg-gradient4.less, test/less/errors/svg-gradient4.txt, test/less/errors/svg-gradient5.less, test/less/errors/svg-gradient5.txt, test/less/errors/svg-gradient6.less, test/less/errors/svg-gradient6.txt
Now you can compile:
```
div {
background: svg-gradient(to bottom, red 0, orange 20%, yellow 30%, green 50%, blue 70%, indigo 85%, violet 100%);
}
@colors: red 0, orange 20%, yellow 30%, green 50%, blue 70%, indigo 85%, violet 100%;
div {
background: svg-gradient(to bottom, @colors);
}
```
Also see: http://stackoverflow.com/questions/26424473/less-svg-gradient-function-with-multiple-variables
=> allow a list of colors as argument for the svg-gradient function

lib/less/tree/directive.js, lib/less/tree/media.js, lib/less/tree/selector.js, lib/less/visitors/import-visitor.js, lib/less/visitors/join-selector-visitor.js, lib/less/visitors/to-css-visitor.js, test/css/directives-bubling.css, test/less/directives-bubling.less
Related to #1691 and #2104 
Directives are changed to work the same way as media. The biggest code change is that the `rules` property of `directive.js` contains an array instead of just a ruleset. 
Directive bubbling ends at the closest directive or media, e.g. this remains unchaged by compilation:
````
@media print {
@supports (upper: test) {
@supports not (-webkit-font-smoothing: subpixel-antialiased) {
@media screen {
nested {
property: value;
}
}
}
}
}
````
=> Bubbling of nested directives

appveyor.yml, bin/lessc, lib/less/functions/color.js, lib/less/functions/function-caller.js, lib/less/functions/types.js, lib/less/tree/dimension.js, lib/less/tree/import.js, lib/less/visitors/extend-visitor.js, lib/less/visitors/to-css-visitor.js, test/css/functions.css, test/css/legacy/legacy.css, test/less/functions.less, test/less/import-reference.less, test/less/import/css-import.less, test/less/legacy/legacy.less
should fix https://github.com/less/less.js/issues/2464
=> do not output when referencing

lib/less/parser/parser.js, test/css/detached-rulesets.css, test/less/detached-rulesets.less, test/less/errors/detached-ruleset-4.less, test/less/errors/detached-ruleset-4.txt
This fixes #2496, allowing detached rulesets to be allowed as mixin argument defaults.
For example:
```less
.mixin(@size: 30px; @padding: 30px; @additions: {}) { // the "@additions: {}" used to error
height: @size;
width: @size;
padding: @padding;
@additions();
}
.no-additions {
.mixin();
}
.additions {
.mixin(@additions: {color: white;});
}
```
compiles to
```css
.no-additions {
height: 30px;
width: 30px;
padding: 30px;
}
.additions {
height: 30px;
width: 30px;
padding: 30px;
color: white;
}
```
=> Allow detached rulesets as mixin argument defaults

lib/less/parser/parser.js, lib/less/tree/directive.js, lib/less/visitors/join-selector-visitor.js, test/css/directives-bubling.css, test/less/directives-bubling.less
When directives bubble up to global scope, selectors are no longer
folded into directives that do not logically allow them.
Fixes #2511
=> Fix selectors folding into directives

bin/lessc
Straight revert of everything in PR #2510. The issue raised in #2508 should be closed as "wont fix". See conversation in PR #2510.
This PR supercedes #2514 which should probably just be rejected.
=> re: #2508 - revert #2510 - undo all fixes. issue == WONTFIX

lib/less/tree/import.js, test/css/import.css, test/less/import/import-test-a.less
Fixes #2516.
Actually I'm not quite sure: maybe this simplification is too liberal but I did not find any weird consequences except that things like `@import ~"some.less";` now work too. Any other value types won't pass through the parser anyway.
=> Quick fix for naked `url` imports

lib/less-rhino/index.js, lib/less/parser/parser-input.js, lib/less/parser/parser.js, lib/less/source-map-output.js, lib/less/tree/dimension.js, lib/less/visitors/extend-visitor.js, package.json, test/browser/runner-global-vars-options.js, test/browser/runner-main-options.js, test/plugins/visitor/index.js
I did not modify `lib\less-rhino\index.js` indents though (just suppressed the corressponding errors for the file) as there're too many (mostly `//` at the start of line).
=> Fix formatting to meet jscs settings

lib/less/functions/string.js, test/css/functions.css, test/less/functions.less
Fixes #2480 as well as similar code with other non-primitive value types. 
E.g.:
```
replace("007", "0", #135); // "#11335507"   / was "undefined07"
replace("007", "0", 2em);  // "2em07"       / was "207"
%("foo-%s", #123);         // "foo-#112233" / was "foo-undefined"
%("bar-%s", 4px);          // "bar-4px"     / was "bar-4"
// etc.
```
=> Proper non-primitive value replacement for `%` and `replace`

bin/lessc, lib/less-node/lessc-helper.js, lib/less-rhino/index.js
Add support for `:` or `;` path separators in `--include-path` regardless of platform. Understands absolute paths with Windows drive letters (ie. `some/relative/dir/:C:\absolute\path`).
Before this change it was impossible to specify custom include paths that would work on Windows as well as other platforms.
=> Add support for `:` or `;` path separators in `--include-path`

lib/less/tree/ruleset.js
Some frames may have no `rules` and `Ruleset.prototype.find` fails with those at https://github.com/less/less.js/blob/v2.5.0/lib/less/tree/ruleset.js#L287 because of `null.forEach`.
I suppose this can affect only programmatic usage of `find` (e.g. within a plugin or so, I stepped into this with a "mixin definition default parameter values" frame).
=> Fix `Ruleset.prototype.find` failing for certain frames

lib/less/tree/mixin-definition.js, lib/less/tree/ruleset.js, test/less/mixins-guards.less
Fixes undefined guard variables when a namespaced mixin is invoked in global scope (#2558).
=> Fix for #2558

lib/less-browser/bootstrap.js, lib/less-browser/index.js
Starting in 2.0, stylesheet loading became asynchronous, through the
usage of promises for both calculating the list of stylesheets and the
initial call to `less.refresh()`. This resulted in visual issues while
loading on some browsers (noticed in Firefox and Safari), along with
breakages of any custom JavaScript that depended on the computed style
of elements on the page, due to race conditions.
This change preserves the promise for initial page loading, in order to
retain support for `less.pageLoadFinished`, but immediately executes the
stylesheet scan (through a new `less.registerStylesheetsImmediately`
function) and the `less.refresh()` call. That resulting behavior matches
versions of less prior to 2.0.
This unveiled a regression in registering functions, both in the browser
and in …
=> Fix synchronously loading/applying stylesheets on page load.

lib/less/parser.js, lib/less/tree/mixin.js, test/less/mixins-args.less
This adds support for expanding arguments that were collapsed using  `.mixin(@foo; @rest...) { }` by being able to write `.mixin2(@rest...);`
An example file that uses this feature extensively can be found at https://gist.github.com/philschatz/839d32ef87bc22ba5231
Also, thanks for adding plugin support! If you're interested, I've used it for:
1. [dead-simple CSS Code Coverage](https://github.com/philschatz/css-coverage.js) for Mocha/Jasmine+BlanketJS and http://coveralls.io (and [Demo](http://philschatz.github.io/css-coverage.js/test/mocha-demo))
2. [CSS Polyfills library](http://philschatz.com/css-polyfills.js/) that implements several CSS3 Module Drafts from W3C (and [GitHub](https://github.com/philschatz/css-polyfills.js))
=> Add ellipsis support when calling a mixin

Gruntfile.js, bin/lessc
Undefined source map should result in an empty map file. Should fix #2430
=> Undefined source map should result in an empty map file. 

.gitignore, lib/less/tree/expression.js, lib/less/tree/rule.js, test/css/import-reference.css, test/less/import/import-reference.less
This pull fixes #2675.
As described in the issue, in-value comments are not currently preserved in when referenced. This patch adds reference marking to nodes below rules and expressions if markReferenced is available.
No changes in benchmark runtime outside of test noise levels.
=> Reference inline comments.

lib/less/parser/parser.js, lib/less/tree/color.js, test/css/comments2.css, test/css/compression/compression.css, test/css/extract-and-length.css, test/css/functions.css, test/css/mixins-args.css, test/css/scope.css, test/css/strings.css, test/css/url-args/urls.css, test/css/urls.css, test/css/variables.css
Keep shorthand color form the same way as named colors are kept. Fixes #2481 - Interpolated selectors and three letters long id selectors.
=> Keep shorthand color form the same way as named colors are kept.

lib/less/tree/anonymous.js, lib/less/tree/import.js, lib/less/visitors/to-css-visitor.js, test/css/import-reference.css, test/less/import-reference.less, test/less/import/import-inline-invalid-css.less, test/less/import/import-reference.less
Import inline located inside file imported by reference should not be present in output. Fixes #2620
=> Fixes import by reference inlines source's inline imports - 2620

lib/less/tree/mixin-definition.js, test/css/mixins-args.css, test/less/mixins-args.less
Named argument in mixin call counted against requires argument with different name in mixin definition. #2645
=> Parametric mixins: parameters don't match error

lib/less/functions/math-helper.js, lib/less/functions/math.js, lib/less/functions/number.js, test/less/errors/percentage-non-number-argument.less, test/less/errors/percentage-non-number-argument.txt
Percentage should work the same way as other math functions (round, floor,etc) and throw error on NaN. #2553
=> `percentage` function should throw error if result would be `NaN`

lib/less/visitors/import-visitor.js
Currently LESSC fails if you have an optional import, the import is missing, and source maps are enabled (#2599).
This changes the import visitor to skip the import if it's optional AND missing.
=> Skip missing optional imports

lib/less/parser/parser.js
=> Allow underscore in a dimension unit

Gruntfile.js, lib/less-browser/image-size.js, lib/less-browser/index.js, test/browser/less/errors/image-height-error.less, test/browser/less/errors/image-height-error.txt, test/browser/less/errors/image-size-error.less, test/browser/less/errors/image-size-error.txt, test/browser/less/errors/image-width-error.less, test/browser/less/errors/image-width-error.txt
Throw a proper exception instead of failing to undefined error when using image-size functions in browser version of less.
Resolves #2737
=> Fail when image-size functions are used in browser-less.

lib/less/parser/parser.js, test/css/mixins-guards.css, test/less/mixins-guards.less
This should fix #2705 - Small feature tweak - keyword "or"
=> Added "or" keyword and allowed arbitrary logical expression in guards.

lib/less/parser/parser.js, test/css/no-strict-math/no-sm-operations.css, test/css/operations.css, test/index.js, test/less-test.js, test/less/no-strict-math/no-sm-operations.less, test/less/operations.less
Named colors inside expressions are will be parsed as colors.
=> Parsing Error "Unrecognised input" for color operations with color names #2124

lib/less/parser/parser.js, test/css/mixins-guards.css, test/less/mixins-guards.less
=> Logical operator and now has higher precedence then logical operator or.

lib/less/parser/parser.js, test/css/css-3.css, test/less/css-3.less, test/less/errors/parse-error-media-no-block-1.txt, test/less/errors/parse-error-media-no-block-2.txt, test/less/errors/parse-error-media-no-block-3.txt
Fixes #2770.
---
This does *not* fix #2639 (i.e. non-block directives do not bubble).
(I suppose enabling bubbling for all unknown at-rules by default would be fine, so I was thinking of doing this in this PR too. But since I don't quite understand the bubbling implementation itself and can't perform any deeper debugging I guess I'll leave this modification for someone else (after all it's a bit beyond #2770 scope anyway and more a subject of #2639)).
=> Allow unknown non-{}-block at-rules

lib/less-browser/bootstrap.js, lib/less-browser/cache.js, lib/less-browser/file-manager.js, lib/less-browser/index.js, package.json
This came up for me on a project where there are "cobranded" versions of the same site. I decided to try rendering the cobranding CSS in the browser, which is when I discovered cache was automatically turned off if modifyVars were set at all. So, I added caching with custom vars.
I also wanted the page rendering to be blocked until styles were done, but was having the same issue as #2384. Since "sync" rendering took 7-8 seconds and "async" rendering took about half a second, I decided to fix this. Not sure if docs should be updated to reflect that XHR is always async. What's nice about this is that the default value should make everything a zillion times faster for people using Less in the browser.
=> Fix for #2384 and caching enabled with modifyVars set

lib/less/parser/parser.js, test/css/comments2.css, test/less/comments2.less
=> Fix comments after named color regression

lib/less/parser/parser.js
It is significantly faster to use instanceof operator for type checking instead of class comparison (jsperf test:http://jsperf.com/functiontype ). The optimization is to put instanceof check at first place.
=> use instanceof operator instead of class comparison optimization

lib/less/parser/parser.js, test/css/no-strict-math/mixins-guards.css, test/less/no-strict-math/mixins-guards.less
This fixes #2798 - left part of inequality could not be enclosed in parenthesis.
=> Guard expressions regression in 2.6.0 (#2798)

lib/less/source-map-output.js
=> Make sourcemap generation a bit faster

lib/less/functions/color.js, test/css/functions.css
This PR cleans up the contrast function so that it actually does what it is supposed to! There's a minor BC break in that it no longer uses the threshold param, which is also what SASS has done, but it's unlikely this will actually affect anyone.
Note that I have trashed some earlier commits in my repo that were based on the wrong revision in favour of this single commit.
=> Update contrast function and tests, fixes #2743

bin/lessc
Since nodejs/node@08085c49b6e, which will be part of Node.js v6.0, functions from the `path` core module (like `dirname`) will require the input to be a string.
Because `.sourceMapFullFilename` and `.sourceMapInputFilename` in bin/lessc may be `undefined`, default to passing `'.'` to `path.dirname` instead. (In Node ≤ v5.x, `path.dirname(undefined) === '.'`.)
Disclosure: I basically don’t know anything about less internals. What I know is that this fixes my build; there’s a good chance that there is a more appropriate solution for this problem. I also have no idea where a test for this particular problem would go, but since this issue can be reproduced by simply running `lessc <input>`, I don’t know if that’s even necessary.
Also, [this …
=> bin/lessc: Make sure path.dirname gets passed strings

lib/less/parser/parser-input.js
The AST didn't include the contents of single line comments because of a tyop in a property name.
I used
```
function lessAST(filename, options) {
options = options || {};
options.filename = path.resolve(filename);
return new Promise(function (res, rej) {
fs.readFile(filename, 'utf8', function (err, data) {
if (err) {
rej(err);
} else {
res(data);
}
});
}).then(function (data) {
return new Promise(function (res, rej) {
less.parse(data, options, function (err, tree) {
if (err) {
rej(err);
} else {
res(tree);
}
});
});
});
}
lessAST(filename).then(function (tree) {
fs.writeFile('tmp.json', JSON.stringify(tree, null, 2));
});
```
to view the AST locally. I haven't yet written any tests for this particular case.
=> Fix AST to include text for single line comments

lib/less/visitors/to-css-visitor.js
This line is unreachable. This is not just about code style, it actually also raises a compilation error when I try to include less.js in a TypeScript project (the TypeScript compiler performs some checks on the input .js files as well).
=> Remove unreachable code

bin/lessc
I'm using `lessc` with Qt/C++ and up until recently I've just been regenerating the stylesheets, but I thought that this could be faster.
I dug around and found the `depends` flag and it sped up my build process 0 to :100: real quick.
The only downside is that when lessc is invoked twice, it will generate output twice.  I actually only need the dependencies with no output, and then at a later stage during `make`, the actual output.  I see here (https://github.com/less/less.js/issues/2476) that it's a nice to have feature, so here it is.
The new option is `-Mn` for short or `--depends-no-output`.  It will exercise the same code path as `depends` but skip the output stage if `depends_no_output` is `true`.
=> make --depends generate no CSS output

lib/less/environment/abstract-file-manager.js
In `extractUrlParts` method of `environment/abstract-file-manager` module there is an error in regular expression. Due to an this error occurs incorrect extraction of the host part from URL.
For example, we have URL - `/Content/less/`. Due to an error we get the host part equals to `/Content/`, but it should be `/`.
=> Fix invalid extraction of the host part from URL

bin/lessc
This commit replaces the old control flow of exiting the process when an error occurred which swallowed the error in some situations (https://github.com/less/less.js/issues/2881). It also adds process.exitCode = 1 in some error situations that have previously been reported as exitCode = 0. Additionally, it adds a listener for "unhandledRejection" to also catch errors caused by rejected promises.
This pull-request incorporates https://github.com/less/less.js/pull/2882
If you don't want to support node 0.10.x anyway, I can also push a simplified version. Then we probably also should remove the `engine` property from the `package.json`.
=> Fix error reporting of lessc executable II

.travis.yml, appveyor.yml, package.json
Addresses #2898.  Instead of attempting a manual download of
PhantomJS, use the npm package phantomjs-prebuilt and the
environment variable `PHANTOMJS_CDNURL` as suggested in
the comment at https://github.com/ariya/phantomjs/issues/13953#issuecomment-200862297.
=> Download PhantomJS from CDN

.travis.yml, appveyor.yml
CI Build Fixes.
In Short:
* Enable Travis Cache to mitigate phantomjs download issues.
* Enable Travis & appveyor <retry> functionality to avoid race condition on CI builds
and old node.js version (0.10/0.12)
Details:
Using <https://bitbucket.org/ariya/phantomjs/downloads/>
to download phantom (on travis)  instead of <http://cnpmjs.org/downloads>
because Travis downloads from http://cnpmjs.org/downloads are horribly slow (30k/s)
and seem courrpt most of the time (smells like throttling)
Travis caching is by branch + build env (node version).
But it has a fallback to using the cache from the default branch
so it should help even with pull requests (which are new branches).
Secondly using **travis_retry** and **appveyor_retry** for **npm install**
to workaround race condition on with npm …
=> CI Build Fixes.

lib/less/source-map-builder.js, lib/less/source-map-output.js, test/less-test.js
As discussed in #1781, the sourceMapBasepath option has no affect on the sourceMapURL value output in the css file. This pull request fixes the issue.
There do not currnetly appear to be any tests for the sourceMapURL CSS appendage.
=> Fixed sourceMapBasepath bug as the option had no affect on the sourceMapURL value.

bin/lessc
When no second argument is given, `output` is undefined. Passing an undefined variable to `path.basename` silently stops the program.
Pull request sent to the master branch, so it might be releasable in the 2.x version. Can be sent to 3.x if that is preferred.
Fixes #2987.
Alternative solutions welcome ofc :smile:
=> Fixes #2987, --source-map-map-inline works as expected

bin/lessc, lib/less-node/index.js, lib/less/less-error.js, test/index.js, test/less-test.js
This fixes my initial concern of this issue: https://github.com/less/less.js/issues/2951
Firstly, I want to drop a few facts about [Errors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) in Javascript.
1. It has 3 standard fields: `name`, `message`, `stack` and **might have** any number of additional, user-defined fields. Generally, such fields are designed to keep different **pieces** of information related to the error.
2. It has it's own `.toString()` method which overrides default `Object.prototype.toString()`. This method is designed to create an as detailed message for the developer as possible using those informational fields.
3. Error might have user-defined methods to create specific sets of information out of informational fields for …
=> Refactor LessError and lesscHelper.formatError

lib/less/tree/import.js, test/css/import.css, test/less/import.less
Right now, an import like `@import "directory/css";` is interpreted as a CSS import, because the path contains `/css`.
Based on https://github.com/less/less.js/issues/2364#issuecomment-68601978, it seems that the intent is to create a CSS import if the word `css` appears as a _URL parameter_. But appearing after a forward slash doesn't indicate a URL parameter; it just indicates a path.
An alternative would be to parse the import path using [url.parse](https://nodejs.org/docs/latest/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) and to look for `css` in the query string or the hash. Please let me know what solution you'd prefer, and I'll adjust as needed.
Refs https://github.com/less/less.js/issues/2364
=> Allow less imports of paths like 'dir/css'

package.json
Compiling following less code:
``` less
@import (less) url(http://example.com/somefile.less);
```
Will fail with if npm 'request' package is not installed:
```
FileError: optional dependency 'request' required to import over http(s)
```
=> Added 'request' as optional dependency.

lib/less/visitors/to-css-visitor.js, test/css/merge.css, test/less/merge.less
The primary purpose of this update was just a minor clean up, but I also changed behaviour of merging `!important` rules according to https://github.com/less/less.js/issues/2367#issuecomment-304703113 (note this does not fix the #2367 itself - that's another story).
=> Update mergeRules 

package.json
See: https://github.com/less/less.js/issues/3104, 
https://github.com/request/request/issues/2772
This PR pins the version of request to still support Node v0.12.x or greater.
=> pinned request dep to v2.81.0

Gruntfile.js, lib/less-node/file-manager.js, package.json, test/css/import-module.css, test/import-module/one/1.less, test/import-module/one/two/2.less, test/import-module/one/two/three/3.less, test/import-module/package.json, test/less/import-module.less
This should fix issue: https://github.com/less/less.js/issues/3115 & I'm hoping a few of the other issues I have seen around paths & webpack?
=> Issue3115 ext in node path

package.json
The version of mime that is referenced is listed on Node Security for having a RegEx-DoS:
- https://nodesecurity.io/advisories/535
- https://github.com/broofa/node-mime/issues/167
This PR updates the optional dependency to use the `1.x` version that does not have this vulnerabiltiy (`1.4.1`).
=> Mime update

.travis.yml, appveyor.yml, package.json
[node support version](https://github.com/nodejs/Release#release-schedule)
Close #3121
=> Drop node 0.10 and 0.12 and added node 9 matrix testing

lib/less/import-manager.js
Stumbled upon this working on https://github.com/webpack-contrib/less-loader/pull/242.
See an instance of the mentioned race condition here: https://ci.appveyor.com/project/webpack-contrib/less-loader/build/1.0.46/job/mbywf90cimqkjee5
It happens when processing files like this:
```less
@import (less) "some/css.css";
@import (inline) "some/css.css";
```
=> `inline` and `less` imports of the same name = race condition

CONTRIBUTING.md, package.json
So contibutors don't have to install grunt globally to run tests which is a good tone.
=> Add "grunt-cli" package to "devDependencies" at package.json

.travis.yml, package-lock.json, package.json
#3179 typescript definitions of source_map are available as part of source-map package from 0.6.0 . 
Needed by downstream projects. hence upgrading source_map to 0.6.x
=> update source_map to 0.6.x 

CHANGELOG.md
Mention the upgrade of source-map library and necessary minimum compatibility mode of node 6
=> docs: add to changelog

lib/less/import-manager.js
This is handy when you're trying to scour your logs to figure out why a file was not being included. :)
=> Less Importer: Throw some notice when a file is skipped

lib/less/parser/parser.js, lib/less/tree/element.js, lib/less/tree/mixin-definition.js, lib/less/tree/ruleset.js, lib/less/tree/selector.js, lib/less/utils.js, lib/less/visitors/extend-visitor.js, test/css/parse-interpolation.css, test/less-test.js, test/less/parse-interpolation.less
* If an element is a variable, this re-parses once evaluated to see if it contains any selectors - Fixes #1421 #3098 #1817 #1694 #2544 #1546 #2080 #2909
=> Fixes #1421 - re-parses variable-interpolated elements to selectors

lib/less/tree/ruleset.js, test/less/extract-and-length.less
Looks like I introduced a bug with the late parsing feature, where a value parsed as a number was trying to get re-parsed when referenced and would cause string parsing failures. Fixes #3195.
=> Fixes #3195 - already-parsed node can't re-parse

lib/less-node/file-manager.js
=> Fixes #3185 - Invalidate less-node file cache if modified

lib/less-browser/cache.js
The problem this fixes is the following: Assume `modifyVars` is not used, i.e. it's `null`.
In `cache.setCSS`, the `:vars` cache item is not set, because `modifyVars` is falsy in [this `if` statement](https://github.com/less/less.js/blob/566f42862e5191d360aff418dd81034615d1e704/lib/less-browser/cache.js#L17).
Therefore, in `cache.getCSS`, we're retrieving a [non-existent item from the cache](https://github.com/less/less.js/blob/566f42862e5191d360aff418dd81034615d1e704/lib/less-browser/cache.js#L29), and so `vars` is `null`.
But `modifyVars`, which is `null` at function call time, is them [defaulted](https://github.com/less/less.js/blob/566f42862e5191d360aff418dd81034615d1e704/lib/less-browser/cache.js#L31) to `{}`. In particular, in the [check whether the cache is …
=>  fix: browser cache is always considered stale if .modifyVars wasn't set

lib/less/functions/types.js, lib/less/tree/variable.js, test/css/calc.css, test/less/calc.less
Fixes #3235 - Vars storing calculations don't crunch the calculation if the var is used in calc.
The solution here is a bit of a hack, but it shouldn't affect performance. Basically, if we're "inside" a `calc()` (in the evaluation stage), it wraps any vars during evaluation as a function call. This switches the math back on in the `Call` Node, and evaluates all the arguments to the call node before merging the value into `calc()`.
=> Fixes #3235

Gruntfile.js, bin/lessc
This also adds tests to check lessc's options handling, though they're incomplete.
=> Fix #3281: console.warning → console.warn

lib/less/functions/color.js, lib/less/parser/parser.js, lib/less/tree/color.js, test/css/colors.css, test/css/functions.css, test/less/colors.less, test/less/errors/color-func-invalid-color.txt, test/less/errors/color-invalid-hex-code.less, test/less/errors/color-invalid-hex-code.txt, test/less/errors/color-invalid-hex-code2.less, test/less/errors/color-invalid-hex-code2.txt
Fixes #3290, #2986, #3176, #1665
- Allows #RRGGBBAA colors
- Outputs color functions as-is when there are unrecognized properties (allows using CSS variables for args, for example)
- Keeps colors in the same color space when possible. e.g. `spin(hsl(50, 1%, 10%), 10)` becomes `hsl(60, 1%, 10%)` vs converting to `rgba()`
- Adds the `rgba(<Color> [, <opacity>])` and `hsla(<Color> [, <opacity>])` 1- or 2-argument forms for those functions
=> Color function updates - #RRGGBBAA and CSS Variables

lib/less/functions/list.js, test/css/functions-each.css, test/less/functions-each.less
While attempting to upgrade a Bootstrap Less port to use `each()` (https://github.com/seanCodes/bootstrap-less-port/pull/12), I saw that there were still some gaps for porting Sass to Less code. Specifically, when looping X number of times based on a variable value. (This has been discussed in numerous issues, including as early as #249 and #2270.)
This PR fills a major gap by adding a very modest list-generating `range()` function modelled after Lodash / PHP / others. Coupled with `each()` it provides a native replacement for a Sass `@for` loop (along with letting you generate range lists for any other general purpose). This solves `for` loops without the syntactic burden of adding a new paradigm. It simply creates and populates a list in a declarative way.
Like Lodash, the function …
=> Adds range() function for lists

lib/less/import-manager.js
This one fixes #3336
The `context` object is cloned, so this is safe to modify. It's also being modified in line 145 to append the extension.
=> Use the correct mime type when loading a plugin

lib/less-browser/bootstrap.js
The `key` variable in `bootstrap.js` is not properly declared, which causes it to be added to the global `window` object.
This PR declares the `key` variable as `var`
=> Do not pollute window object in less-browser bootstrap

lib/less/source-map-output.js
When building with angular-cli and lazy loaded modules, there are empty files with no content. This produces an unfortunately cryptic error message: "cannot call substring of undefined. File 'undefined', line 'undefined'"
After much investigation I found this to be the source of the issue. I don't really know root cause, but I think it has to do with webpack's module splitting. Maybe files in split modules aren't immediately available? At any rate, this fixes it and seems in line with behavior at the start of the file.
=> Ignore undefined content in generating source maps

dist/less.js, lib/less/tree/operation.js
fix [Issues#3327](https://github.com/less/less.js/issues/3327)
Operation.prototype.accept = function (visitor) {
//this.operands = visitor.visit(this.operands);
this.operands = visitor.visitArray(this.operands);
};
=> Operation.prototype.accept Issues#3327

lib/less/parser/parser.js, lib/less/tree/namespace-value.js, test/css/namespacing/namespacing-3.css, test/less/namespacing/namespacing-3.less
!important keyword was being parsed inside VariableCall, which was unnecessary and leads to the bug. Instead, we can check/parse it along with the declaration parser.
Similar logic may apply to mixin-call but couldn't reproduce a bad case.
=> Fixes #3430: Removed unnecessary 'important' from NamespaceValue.

lib/less/visitors/visitor.js
When a visitor hook returns an array of nodes for replacement, the accept calls are not made.
Returning an array of node when the plugin implementation `isReplacing` is set seems to be correctly supported in the `visitArray` function implementation.
-L
=> - Fixed replacer when visitor returns array of nodes

lib/less-browser/file-manager.js, lib/less-node/file-manager.js, lib/less/environment/abstract-file-manager.js, test/css/import-once.css, test/less/import-once.less, test/less/import/import.once.test.d.less
Fixes #3288
This PR consist of three parts: importing files in node, importing files in browser, and unit test.
Fix described in issue isn't full because if file has dots in name it doesn't mean that we shouldn't add extension. That's why we should try to load file with and without extension.
As an example:
1) hello.css - this file has extension and we shouldn't add .less at the end.
2) hello.world - this file doesn't have extension and we probably should add .less at the end.
Thanks a lot.
=> Import file with dots in file name

package.json
request v2.83 uses hawk package (which has been moved to @hapi/hawk) this causes  warning during package installation.
The latest version of request does not have the dependency
=> Update request to v2.88.0

lib/less/contexts.js, test/css/calc.css, test/less/calc.less, test/sourcemaps/custom-props.json
In issue #3393, it was found that Less does not properly exit out of calc mode after using it. This causes subsequent variables to be incorrectly evaluated, which results in errors. The code checks if the calculation stack is empty by checking `!this.calcStack`, but this does not evaluate to false. This was changed to checking if `this.calcStack.length` is 0, which does evaluate to false.
**Note**: The changes introduced by this PR also caused changes in the sourcemap test output, which is why I modified that as well. I'm not sure if this is right or wrong.
=> Properly exit calc mode after use

bin/lessc, lib/lessc.js, package.json
Closes #3487 
`minimist` has the vulnerability. By removing `mkdirp@0.x` (which is deprecated anyway) we get rid of `minimist`. 
Note that we already have to use an outdated version of `make-dir` since less supports node 6 (has reached end-of-life a year ago) while `make-dir@latest` only supports node 8 (which also reached end-of-life since end of last year).
=> fix: Use make-dir instead of mkdirp

lib/less/parser/parser.js, test/less/errors/invalid-color-with-comment.less, test/less/errors/invalid-color-with-comment.txt
While investigating #3443, it was found that the evaluation of the expression became stuck in an infinite loop, filling up the `entities` array until Less runs out of memory. The cause appears to be the attempted evaluation of a comment as an entity, which should have been caught just beforehand but for some reason wasn't. Maybe an issue with cleaning up the loop variable?
A second check has now been added to the entity retrieval, since an entity can also be a comment. This fix removes the value from `e` if that is the case, preventing the infinite loop.
=> Additional check to avoid evaluating an expression if it is a comment

lib/less-node/plugin-loader.js, lib/less/import-manager.js, package.json, test/css/import.css, test/index.js, test/less/import.less
Currently the only way to compile Less code synchronously is by setting `syncImport: true`. But as described in #3294, it cannot work when it involves plugins. In fact `loadPlugin` didn't have a sync version. This PR added a `loadPluginSync` method to fix this problem.
---
~~PS. I didn't quite understand how tests work so tests are not included. Any help would be appreciated.~~
---
**Please note: compiled files are not included in this PR.**
=> fix(#3294): use loadFileSync when loading plugins with syncImport: true

bin/lessc, lib/less-node/lessc-helper.js, lib/less/source-map-builder.js, test/index.js, test/less-test.js, test/less/sourcemaps-disable-annotation/basic.less, test/sourcemaps-disable-annotation/basic.json
**Small doubts** 
Shall I use positive form for the property? I mean using `appendSourcemapUrlAnnotation`, for example,  instead of `disableSourcemapAnnotation` sounds more straightforward for me. In other words, `disableSourcemapAnnotation: false/true` looks a little bit confusing.
`--source-map-no-annotation`, on the other hand, looks ok for me since it does not have true/false value with it.
=> Resolve #3398 Add flag to disable sourcemap url annotation

package-lock.json, packages/less/package-lock.json, packages/less/package.json, packages/less/src/less-node/url-file-manager.js, packages/less/test/index.js, packages/less/test/less-test.js, packages/test-data/less/import-redirect/import-redirect.less
Quick overview of the changes:
1. Replace `native-request` with [needle](https://www.npmjs.com/package/needle) - hopefully small enough http client to not be a burden.
2. Add [nock](https://www.npmjs.com/package/nock) based test to verify correct work of the redirect.
3. Moved `logger.addListener` call outside of `lessTester` factory function in `less/test/less-test.js`. This was necessary to avoid registering the same listeners twice as for the test it was necessary to instantiate `lessTester` one more time.
4. Created one more instance of `lessTester` in `less/test/index.js`. This is necessary since tests in the test suite are not isolated and leave `less` instance in the state in which remote imports are completely broken.
=> Fix #3576 import redirects. Replace native-request with needle.

packages/less/src/less-node/url-file-manager.js
In the case of a network issue, there's an error but no response, so no statusCode, This fixes it
Fixes #3594
=> Fix expected response when there's a socket error

packages/less/src/less/tree/node.js
These fields are accessed by other tools such as parcel (for resolving local
asset URLs). As per 257efdd6884268af27beaceda467fd3a4aea5e08 the behavior with
(at least) parcel for relative paths in sub-directries changed. Prior to that
commit (last release 3.12.2) assets were resolved relative to the less module
that contains the `url(..)`. From release 3.13.0 parcel resolves assets relative
to the root less module, because no `currentFileInfo` is available.
This is caused by tree nodes setting their prototype to an instance of
`Node`. This leaves the `self` reference in `Node`s constructor pointing to the
prototype, not the actual instance the data is set on. Replacing this with
properties defined on `Node`s prototype fixes this.
=> Fix `currentFileInfo` and `index` properties on nodes

packages/less/src/less/functions/function-caller.js, packages/test-data/css/math/parens-division/parens.css, packages/test-data/css/math/strict/parens.css, packages/test-data/less/math/parens-division/parens.less, packages/test-data/less/math/strict/parens.less
Try to fix https://github.com/less/less.js/issues/3616
If you write `less` (v4 parens-division default) code like follow:
```less
.parens-issues-3616 {
bar: if(false, 666, 888 / 444);
bar2: if(false, 666, (666 / 333));
bar3: if(false, 666, ((444 / 222)));
}
```
**`ParseTree -> ruleset eval -> declaration eval -> value eval -> expression eval -> call eval -> functionCaller.call -> If -> operation eval`**
|  Input  | Expected  | Result |
|  ----  | ----  | ---- |
| `bar2: if(false, 666, (666 / 333)); ` | `bar2: 2;` | `bar2: 666 / 333;` | 
In our expacted logic the `Operation`'s eval output should be a `Unit` which value is `2`.
> `(666 / 333)` compile to a `Expression` which contains a `Operation` 
The `Operation`'s eval logic
```js
//  packages/less/src/less/tree/operation.js
eval(context) …
```
=> Fix #3616 IfStatement requires double parentheses when dividing 

packages/less/src/less-node/url-file-manager.js
The warning for using `@import url` without the optional `needle` dependency incorrectly specifies that `native-request` is the necessary package rather than `needle`.
Relates to the commit https://github.com/less/less.js/commit/ec7487586413f66e3a3da3ff6e5526868450e97b .
=> Fix needle dependency warning typo.

README.md
Add two badges(github actions ci / npm downloads) for better `README.md` information shown.
Even this PR is only a markdwon file change, so skip CI trigger
/cc @matthew-dean 
> https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci
GitHub Actions now supports skipping push and pull_request workflows by looking for some common keywords in your commit message.
>If any commit message in your push or the HEAD commit of your PR contains the strings [skip ci], [ci skip], [no ci], [skip actions], or [actions skip] workflows triggered on the push or pull_request events will be skipped.
=> [skip ci] Add github CI status badge and npm downloads badge

packages/less/Gruntfile.js, packages/less/bin/lessc
fix #3646. hope this will work
add a unit test
forcefully change unsupported input to strings
=> fix #3646, forcefully change unsupported input to strings

packages/less/src/less-browser/utils.js
fix when script run with TamperMonkey or GreaseMonkey tag is null
#3655 fix this
=> fix #3655 for param tag is null

CHANGELOG.md
Add missing changelog info cc @matthew-dean
=> [skip ci]chore: add missing changelog info

.gitignore, packages/less/src/less/parser/parser.js, packages/test-data/css/_main/impor.css, packages/test-data/css/_main/plugi.css, packages/test-data/errors/parse/impor-typo.less, packages/test-data/less/_main/impor.less, packages/test-data/less/_main/plugi.less
Try to fix https://github.com/less/less.js/issues/3660
> We discovered that the regex used for `import` and `plugin` have a `?` at the end of them, which means `@plugi` and `@impor` work as well as `@plugin` and `@import`.
These are defined here: https://github.com/less/less.js/blob/master/packages/less/src/less/parser/parser.js#L1687 and https://github.com/less/less.js/blob/master/packages/less/src/less/parser/parser.js#L1847.
This doesn't look like an intentional decision and more of a regex mistake. See here for example inputs: https://regex101.com/r/NUw7E2/2
Is this correct?  --from @edhgoose
https://github.com/less/less.js/blob/a4b6c8544c077a193a3d39955db76047545f1539/packages/less/src/less/parser/parser.js#L1687
https://github.com/less/less.js/blob/a4b6c8544c077a193a3d39955db76047545 …
=> fix: change keyword plugin and import regexp

packages/less/src/less/parser/parser.js, packages/less/src/less/tree/attribute.js, packages/test-data/css/_main/selectors.css, packages/test-data/less/_main/selectors.less
**What**:
add support for case-insensitive attribute selectors
try to fix https://github.com/less/less.js/issues/3027 https://github.com/less/less.js/issues/3670 https://github.com/go-gitea/gitea/pull/15520 https://github.com/go-gitea/gitea/issues/15565
**Why**:
CSS spec -> https://www.w3.org/TR/selectors-4/#attribute-case
**How**:
https://github.com/less/less.js/issues/3027#issuecomment-828223873
**Checklist**:
cc @matthew-dean
=> feat: add support for case-insensitive attribute selectors

.github/workflows/ci.yml
**What**:
| previous ci config | new ci config |
| :--- | :---- |
| matrix tests node(10/12/14/16) with os(win/mac/linux) | matrix tests node16 with os(win/mac/linux) and node(10,12,14,17) width ubuntu | 
| Total 12 tests suite |  Total 7 tests suite |
**Why**:
Too many Redundant tests ci, reconfig to reduce ci times and failures ( https://github.com/less/less.js/actions?query=is%3Afailure )
**How**:
Change `ci.yml`
**Checklist**:
cc @matthew-dean
=> ci: reduce ci times and add node17 test

packages/less/src/less-node/image-size.js, packages/less/src/less-node/index.js, packages/less/src/less/tree/expression.js
**What**: remove unused vars, except parameters
**Why**: let code be better.
**How**: 
**Checklist**:
=> remove unused vars, except parameters

packages/less/package-lock.json, packages/less/package.json
The issue was traced upstream to needle, and resolved in:
- https://github.com/tomas/needle/pull/392
- https://github.com/tomas/needle/pull/394
- https://github.com/tomas/needle/pull/396
- https://github.com/tomas/needle/pull/398
Closes #3693
**What**: Fix macOS ECONNRESET w/ node v14+
**Why**: Without the upgrade to needle, some more complex less files with https inline imports can fail with ECONNRESET, specifically on macOS w/ node v14+
**How**: The root cause was traced to the dependency `needle`, and fixed there over several PRs addressing various combinations of OS and node version
**Checklist**:
=> fix: Fix https failures on macOS

CHANGELOG.md
**What**:
Add `v4.1.3` CHANGELOG,  fix https://github.com/less/less.js/pull/3722#issuecomment-1150558235
**Why**:
Keep latest CHANGELOG.md for all `Less` user arround the world.
**How**:
Modify `CHANGELOG.md` content
**Checklist**:
=> [skip ci]: add v4.1.3 missing changelog

packages/less/src/less/functions/number.js, packages/test-data/css/_main/functions.css, packages/test-data/less/_main/functions.less
**What**:  get correct `this`
**Why**:  
this === undefined
https://github.com/less/less.js/blob/1eafc06db4ed062761ce6ca65044204cf32308a1/packages/less/src/less/functions/number.js#L54
**How**:
**Checklist**:
=> refactor: Modify this pointer so that it is not empty.

packages/less/src/less/parser/parser.js, packages/test-data/css/_main/permissive-parse.css, packages/test-data/less/_main/permissive-parse.less
**What**:
Added a fix for the parser crashing when a css variable property does not end with a semicolon. Fixes #3698 and Fixes  #3373.
**Why**:
This helps to avoid crashes when importing pre-minified css files from e.g. an npm package. In our case, [cssnano](https://cssnano.co/) always drops the trailing semicolon on the last property. This cannot be disabled without disabling all of whitespace normalization (`normalizeWhitespace` option). Fixing the bug in Less.js fixes this use case for us.
**How**:
When calling `permissiveValue` on a detected css variable, the `untilTokens` parameter is left unset. This defaults it to detecting `;` for ending the value. I've set the parameter to `/[;}]/` instead in order to close variables on either the semicolon (`;`) or the closing curly bracket …
=> Fix #3698 #3373 - parsing variables fail when there is no trailing semicolon

package-lock.json, packages/less/package-lock.json, packages/less/package.json
**What**:
CI crashed, because `puppeteer` not work with github actions operating system (maybe due to old version chorme? I don't know).
https://github.com/less/less.js/actions/runs/3921060243/jobs/6713174574#step:8:560
**Why**:
CI is important for test and project maintenance.
**How**:
Maybe we need upgrade our test infra deps.
**Checklist**:
1. mocha-headless-chrome 
>  mocha-headless-chrome [changelog](https://github.com/direct-adv-interfaces/mocha-headless-chrome/blob/master/CHANGELOG.md#400)
4.0.0
PR https://github.com/direct-adv-interfaces/mocha-headless-chrome/pull/61: Update [puppeteer](https://www.npmjs.com/package/puppeteer) package to 13.1.3 version. Node.js 10 is no longer supported.
> **_But it looks like Node10 CI work as expected ?_**
2. packgae lockfile version
since …
=> fix: make ci work

packages/less/src/less/parser/parser.js, packages/less/src/less/tree/ruleset.js, packages/less/src/less/tree/selector.js, packages/less/test/index.js, packages/less/test/less-test.js, packages/less/test/sourcemaps-variable-selector/basic.json, packages/test-data/less/sourcemaps-variable-selector/basic.less, packages/test-data/less/sourcemaps-variable-selector/vars.less
**Note to reviewer:** There are two potential solutions here, one that fixes the specific issue linked, and one that might be a bit more robust. Filter down to the first commit for the bandaid fix, second commit for the more robust one, third commit for added test. I recommend hiding whitespace changes in the GitHub UI – my editor removed a bunch of unnecessary trailing spaces
**What**:
Fixes https://github.com/less/less.js/issues/3567
Source maps are pointing to the wrong files, and it seems that it points at different files on different runs, causing non-deterministic source map output.
**Checklist**:
**Why** and **How** are included in the below description, which details the problem in the code and the proposed solutions.
Bear with me a bit, this was my first venture into the less …
=> fix faulty source map generation with variables in selectors

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml
**What**:
Change the github actions ci config
**Why**:
Current Node.js LTS version is v18, and v19 has been released.
**How**:
Change the Node.js version in the matrix tests from v16 to the latest LTS version, v18, and add tests for Node.js v19.
**Checklist**:
=> ci: update the ci config

CHANGELOG.md
**What**:
v4.2.0 missing changelog
**Why**:
emmmm, forgot
**Checklist**:
=> [skip ci] add v4.2.0 changelog

packages/less/src/less/parser/parser.js, packages/test-data/css/_main/variables.css, packages/test-data/less/_main/variables.less
**What**:
Fixes issue #3737 where blank CSS variable declarations resulted in parsing errors.
**Why**:
Blank CSS variables are valid.
**Checklist**:
Existing tests are passing locally.
The following Less.js:
```css
*, ::before, ::after {
--tw-pan-x:  ;
--tw-pan-y:  ;
--tw-pinch-zoom:  ;
--tw-scroll-snap-strictness: proximity;
}
```
becomes:
```css
*,
::before,
::after {
--tw-pan-x: ;
--tw-pan-y: ;
--tw-pinch-zoom: ;
--tw-scroll-snap-strictness: proximity;
}
```
=> fix(issue:3737) allow blank variable declarations

packages/less/src/less/parser/parser.js, packages/test-data/css/_main/variables.css, packages/test-data/less/_main/variables.less
**What**:
Fixes variable interpolation issue after previous variable addition.
**Why**:
Current Less.js takes:
```css
@a: 1px;
@b: 2px;
@c: @a + @b;
@radio-cls: radio;
@radio-cls-checked: @{radio-cls}_checked;
.@{radio-cls-checked} {
border-color: #fff;
}
```
and produces:
```css
._checked {
border-color: #fff;
}
```
With fix the CSS is:
```css
.radio_checked {
border-color: #fff;
}
```
**Checklist**:
Tests passing locally. Updated tests for variables.
=> fix(issue:4258) variable interpolation after math

packages/less/src/less/parser/parser.js, packages/test-data/css/_main/variables.css, packages/test-data/less/_main/variables.less
**What**:
Fix for issue #4264. Strip line comments from expressions to avoid invalid CSS output.
**Why**:
Less.js currently takes CSS like:
```css
@items:
// Fruit
apple,
banana,
cherry,
// Vegetables
carrot,
potato,
;
each(@items, {
div#@{value} {
color: blue;
}
})
```
and outputs:
```css
div#apple {
color: blue;
}
div#banana {
color: blue;
}
div#cherry {
color: blue;
}
div#// Vegetables carrot {
color: blue;
}
div#potato {
color: blue;
}
```
With fix the output is:
```css
div#apple {
color: blue;
}
div#banana {
color: blue;
}
div#cherry {
color: blue;
}
div#carrot {
color: blue;
}
div#potato {
color: blue;
}
```
**Checklist**:
Tests passing locally. Updated tests for variables.
=> fix(issue:4264) strip line comment from expression

packages/less/src/less/parser/parser.js, packages/less/src/less/tree/atrule.js, packages/test-data/css/_main/layer.css, packages/test-data/less/_main/import/layer-import.less, packages/test-data/less/_main/layer.less
**What**:
Fix for issue https://github.com/less/less.js/issues/4242 that builds upon https://github.com/less/less.js/pull/4333 to add support for ```@layer``` at-rule.
**Why**:
The ```@layer``` at-rule has 94.47% (https://caniuse.com/mdn-css_at-rules_layer) browser support can support for the at-rule can benefit Less users.  
**Checklist**:
=> fix(issue#4242): add support for layer at-rule
