lib/less-browser/cache.js
see also: http://stackoverflow.com/questions/27722349/less-js-error-msg-failed-to-save/27750286
=> Change error message when caching fails

lib/less/visitors/extend-visitor.js
=> checking for doubles when warning for empty extends

bin/lessc, package.json
Added error handling to file write for both css file and source map file #2408
@lukeapage I added also dependency errno, so please let me know whether you are ok with it. If you are not I will just copy likely errors from errno (it has MIT license so it should be fine). I will merge other small commits by myself if nobody objects for long enough, but I remember you saying once that you want to avoid dependencies.
=> Added error handling to file write 

lib/less/tree/directive.js, test/css/import-reference.css, test/less/import-reference.less, test/less/import/import-reference.less
Keyframes, supports and other directives should work with import reference too.  #2008
=> keyframe mixin doesnt work with import reference

lib/less/import-manager.js, lib/less/parser/parser.js
https://github.com/less/less.js/issues/2145
=> optional imports

lib/less/functions/color.js, test/css/functions.css, test/less/functions.less
=> optional relative amounts for color functions, see#975

Gruntfile.js
=> Fix grunt shell:benchmark command

lib/less/tree/ruleset.js, test/css/extend-selector.css, test/less/extend-selector.less
=> Fixed extend leaking through nested parent selector. 

lib/less/parser/parser.js
=> Disallow whitespace in variable calls (aka ruleset calls, aka DR-calls)

package.json
=> Revert "Update jit-grunt to version 0.10.0"

lib/less-browser/index.js
Hi, I fixed both issues. I tested them locally and I also run standard test. Seems to be OK. I am not sure how to write automatic tests, especially for #2844 which happens randomly and depends on browser communication...
=> Fix for #2812 and #2844 

package.json
Removed this dependency since it not used anymore in the code.
=> removed dependency to package "request" (closes #2870)

.travis.yml, appveyor.yml
Add support for Node.js v8.
Updated .travis.yml and appveyor.yml.
=> Add Node.js v8 to Travis CI and AppVeyor

Gruntfile.js, package.json
[`request`](https://npmjs.com/package/request) is way too large and has way too many dependencies! Use [`phin`](https://npmjs.com/package/phin) instead!
=> Switch from request to phin!

package-lock.json, package.json
The old request package has some vulnerable dependencies inside. So because nsp detected it has to be updated, see: https://nodesecurity.io/advisories/566
https://github.com/less/less.js/issues/3169
=> chore(package): update request to 2.83.0

lib/less/contexts.js, lib/less/parser/parser.js, lib/less/tree/call.js, lib/less/tree/expression.js, test/css/calc.css, test/less/calc.less
Fixes issues with calc flattening parentheses in expressions and also with escaped values in expressions.
=> Fixes #3191

lib/less/parser/parser.js, test/css/edge/namespacing-2.css, test/css/edge/namespacing-media.css, test/less/edge/namespacing-2.less, test/less/edge/namespacing-media.less
=> Tests and parser fixes for namespace values in MQ and mixin args

lib/less/parser/parser.js, test/css/media.css, test/css/variables.css, test/less/errors/detached-ruleset-2.txt, test/less/media.less, test/less/variables.less
=> Fixes issue with parentheses following variable in expressions

package-lock.json, package.json, test/css/3rd-party/bootstrap.css, test/css/3rd-party/bootstrap4.css, test/css/3rd-party/uikit.css, test/index.js, test/less/3rd-party/bootstrap.less, test/less/3rd-party/bootstrap4.less, test/less/3rd-party/uikit.less
=> Fixes #3231 - Adds UIKit, Bootstrap 3, and Bootstrap 4 to verified tests

test/css/css-escapes.css, test/less/css-escapes.less
fixes #3160 (already fixed, just adding tests to prevent regression)
=> Demonstrate 3.7 fixes #3160

lerna.json, packages/less/Gruntfile.js, packages/less/bin/lessc, packages/less/src/less/functions/list.js, packages/test-data/css/namespacing/namespacing-8.css, packages/test-data/less/namespacing/namespacing-8.less
See comment: https://github.com/less/less.js/issues/3368#issuecomment-659623734
=> Bug fixes - fixes #3446 #3368

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/bug.md, .github/workflows/config.yml
Add `bug.md` for bug issue template
Add `config.yml` for better issue navigation
Add `PULL_REQUEST_TEMPLATE.md` for better contribution
cc @matthew-dean Ready for review.
=> [skip ci] Add issue and pull request template for better communication

.github/workflows/ci.yml
**What**:  https://nodejs.org/en/blog/announcements/v18-release-announce/
**Why**: Follow nodejs LTS !
**How**: chang ci config
**Checklist**:
=> ci: add node18 support and drop node17 ci

.github/ISSUE_TEMPLATE/bug.md
**What**:
update the issue template of bug report
**Why**:
see https://github.com/less/less.js/issues/3773#issuecomment-1492561499
**How**:
Update the .github/ISSUE_TEMPLATE/bug.md
**Checklist**:
=> [skip ci] update the issue template of bug report

.github/workflows/ci.yml, package-lock.json, package.json, packages/less/Gruntfile.js, packages/less/test/browser/generator/generate.js, packages/less/test/browser/generator/runner.config.js, packages/less/test/browser/generator/template.js, packages/less/test/browser/generator/utils.js
**What**:
Try to recover windows ci
**Why**:
https://github.com/less/less.js/pull/3814#issuecomment-1685115827
**Checklist**:
=> ci: windows
